---
title: "rjmcmc_normal"
output: html_document
---

## data

```{r}
source("../dir_manager.r")
source(file.path(dir_path,"rjmcmc_normal/rjmcmc.r"))

set.seed(6291117)
n <-  200
# Generate Data
pi.1 <- 2/10
pi.2 <- 3/10
pi.3 <- 5/10

k <- 3
sim_pi <- c(pi.1, pi.2, pi.3)

sim_mu <- c( -5,    0,    5)
sim_tau <- c(2, 5, 1)
sim_sigma <- 1/sqrt(sim_tau)

y <- c()
for(i in c(1:k)){
  y.k <- rnorm(n*sim_pi[i], mean = sim_mu[i], sd = sim_sigma[i])
  cat("simulated mu k= ",i," :", mean(y.k), "\n")
  cat("simulated tau k= ",i," :", 1/sd(y.k)^2, "\n")
  y <- c(y, y.k)
}

X <- sample(y)

# prior
xi <- 0
kappa <- 0.001
a <- 0.1
g <- 0.1
h <- 1
delta <- 1
lambda <- 3
```


### Birth Death Rate

```{r}
source("../dir_manager.r")
source(file.path(dir_path,"rjmcmc_common/birth_death_prob.r"))

max.K <- 10
min.K <- 1
c_val <- 0.5

res <- get_birth_death_pr(max.K, min.K, lambda, c_val)
birth_pr <- res$birth_pr
death_pr <- res$death_pr
```


### Run

```{r}
source(file.path(dir_path,"rjmcmc_normal/rjmcmc.r"))
set.seed(6291117)
iter <- 100000
burn.in <- iter/5

split_accept_count <- 0
combine_accept_count <- 0
birth_accept_count <- 0
death_accept_count <- 0

split_count <- 0
combine_count <- 0
birth_count <- 0
death_count <- 0

# initial value
k <- 5
b <- rgamma(1, g, h)
mu <- sort(rnorm(k, xi, kappa))
tau <- rep(1, k)
pi <- rdirichlet(1, rep(delta, k))
Z <- rep(1:k, length.out=length(X))
tic("Running RJMCMC normal:")
est <- rjmcmc_mixture_normal_random_b(
  iter, X, max.K,# iteration count, data
  xi, kappa, a, g, h, lambda, delta,#  prior parameters
  k, mu, tau, pi, Z, b, # initial value
  birth_pr, death_pr     )
toc()

est1 <- est[[1]]
lst_est1 <- extract_data(est1, burn.in + 1, iter)

all_Z <- est[[2]]
all_Z <- all_Z[(burn.in + 1): iter,]
```

```{r}
source(file.path(dir_path,"rjmcmc_common/utilities.r"))
source(file.path(dir_path,"rjmcmc_common/rjmcmc_plot.r"))


plot_k_trace_and_density(lst_est1)

est_k <- 3

lst_only3 <- remove_all_k_but(lst_est1, est_k)

```

```{r}
source(file.path(dir_path,"rjmcmc_common/rjmcmc_plot.r"))

# plot_rjmcmc_trace_and_density(lst_only3$mu,  "mu", est_k, sim_mu)
# plot_rjmcmc_trace_and_density(lst_only3$tau,  "tau", est_k, sim_tau)
# plot_rjmcmc_trace_and_density(lst_only3$pi,  "pi", est_k, sim_pi)
pp <- plot_rjmcmc_sixpanel(
  mats   = list(mu = lst_only3$mu, tau = lst_only3$tau, pi = lst_only3$pi),
  k      = est_k,
  truths = list(mu = sim_mu, tau = sim_tau, pi = sim_pi),
  trace_alpha = 0.25,
  legend_position = "bottom",
  panel_label_size = 10,
  mu_range = c(-10, 10),
  tau_range = c(0, 10)
)
ggsave(
  file.path(pic_path, "rjmcmc_normal", "rjmcmc", "raw_3", "raw_3.png"),
  pp,
  width = 8,
  height = 10
)

```


```{r}
source(file.path(dir_path,"rjmcmc_common/post_process.r"))

lst_est_after <- filter_by_component_size(all_Z, lst_est1, min_count = 2)

lst_only3_after <- remove_all_k_but(lst_est_after, est_k)

plot_rjmcmc_sixpanel(
  mats   = list(mu = lst_only3$mu, tau = lst_only3$tau, pi = lst_only3$pi),
  k      = est_k,
  truths = list(mu = sim_mu, tau = sim_tau, pi = sim_pi),
  trace_alpha = 0.25,
  legend_position = "bottom",
  panel_label_size = 10
)
```




